#!/bin/sh
### BEGIN INIT INFO
# Provides:          umountfs
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      0 6
# Short-Description: Turn off swap and unmount all local file systems.
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

echo "Deactivating swap..."
swapoff -a

# We leave /proc mounted.
echo "Unmounting local filesystems..."
grep -q /mnt/ram /proc/mounts && mount -o remount,ro /mnt/ram
sync
mount -o remount,ro /
echo "Remounted / as RO..."
sync
umount -f -a -r > /dev/null 2>&1
echo "Detaching..."
ubidetach -d 1 /dev/ubi_ctrl
ubidetach -d 2 /dev/ubi_ctrl

: exit 0
