#! /bin/sh

set -e

export KERNEL=`uname -r`

case "$1" in
start)
    echo -n "Starting init_qcom_audio: "
    insmod /usr/lib/modules/$KERNEL/kernel/arch/arm/mach-msm/qdsp6v2/adsp-loader.ko
    echo "done"
    ;;
  stop)
    echo -n "Stopping init_qcom_audio: "
    rmmod /usr/lib/modules/$KERNEL/kernel/arch/arm/mach-msm/qdsp6v2/adsp-loader.ko
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Incorrect option specified"
    exit 1
    ;;
esac

exit 0
